import type {
  RemaxAdvisor,
  RemaxCommunication,
  RemaxProperty,
  RemaxValueHistory
} from "@/remax-demo/types";

export const remaxDemoAdvisors: RemaxAdvisor[] = [
  {
    id: "pedro-leyva",
    nombre: "Pedro Leyva",
    clase: "A",
    tipoPersonal: "direccion",
    rol: "Director General / Asesor A",
    comisionRate: 0.075,
    activo: true
  },
  {
    id: "alejandra-rios",
    nombre: "Alejandra Rios",
    clase: "A",
    tipoPersonal: "asesor",
    rol: "Captacion premium",
    comisionRate: 0.07,
    activo: true
  },
  {
    id: "mariana-cisneros",
    nombre: "Mariana Cisneros",
    clase: "A",
    tipoPersonal: "asesor",
    rol: "Rentas corporativas",
    comisionRate: 0.07,
    activo: true
  },
  {
    id: "andres-galvan",
    nombre: "Andres Galvan",
    clase: "A",
    tipoPersonal: "asesor",
    rol: "Inversion patrimonial",
    comisionRate: 0.0725,
    activo: true
  },
  {
    id: "daniela-ibarra",
    nombre: "Daniela Ibarra",
    clase: "A",
    tipoPersonal: "asesor",
    rol: "Residencial alto valor",
    comisionRate: 0.07,
    activo: true
  },
  {
    id: "julieta-mora",
    nombre: "Julieta Mora",
    clase: "A",
    tipoPersonal: "asesor",
    rol: "Cierres y negociacion",
    comisionRate: 0.07,
    activo: true
  },
  {
    id: "ricardo-salinas",
    nombre: "Ricardo Salinas",
    clase: "M",
    tipoPersonal: "asesor",
    rol: "Prospeccion zona sur",
    comisionRate: 0.045,
    activo: true
  },
  {
    id: "sofia-campos",
    nombre: "Sofia Campos",
    clase: "M",
    tipoPersonal: "asesor",
    rol: "Captacion digital",
    comisionRate: 0.045,
    activo: true
  },
  {
    id: "valeria-ordonez",
    nombre: "Valeria Ordonez",
    clase: "M",
    tipoPersonal: "asesor",
    rol: "Seguimiento de leads",
    comisionRate: 0.0425,
    activo: true
  },
  {
    id: "diego-ruiz",
    nombre: "Diego Ruiz",
    clase: "M",
    tipoPersonal: "asesor",
    rol: "Apoyo de cierres",
    comisionRate: 0.045,
    activo: true
  },
  {
    id: "karla-soto",
    nombre: "Karla Soto",
    clase: "M",
    tipoPersonal: "asesor",
    rol: "Rentas residenciales",
    comisionRate: 0.04,
    activo: true
  },
  {
    id: "tomas-herrera",
    nombre: "Tomas Herrera",
    clase: "M",
    tipoPersonal: "asesor",
    rol: "Inventario y visitas",
    comisionRate: 0.04,
    activo: true
  },
  {
    id: "patricia-romo",
    nombre: "Patricia Romo",
    clase: null,
    tipoPersonal: "administrativo",
    rol: "Coordinacion operativa",
    comisionRate: null,
    activo: true
  },
  {
    id: "erika-valles",
    nombre: "Erika Valles",
    clase: null,
    tipoPersonal: "administrativo",
    rol: "Control de comisiones",
    comisionRate: null,
    activo: true
  },
  {
    id: "leonel-arias",
    nombre: "Leonel Arias",
    clase: null,
    tipoPersonal: "administrativo",
    rol: "Backoffice de captacion",
    comisionRate: null,
    activo: true
  },
  {
    id: "susana-montes",
    nombre: "Susana Montes",
    clase: null,
    tipoPersonal: "administrativo",
    rol: "Administracion de expedientes",
    comisionRate: null,
    activo: true
  },
  {
    id: "gabriela-perez",
    nombre: "Gabriela Perez",
    clase: null,
    tipoPersonal: "recepcion",
    rol: "Recepcion y agenda comercial",
    comisionRate: null,
    activo: true
  }
];

export const remaxDemoValueHistory: RemaxValueHistory[] = [
  {
    id: "vh-001",
    propiedadClave: "RMX-ACT-201",
    fecha: "2026-01-12",
    valorAnterior: null,
    valorNuevo: 6980000,
    motivo: "Alta inicial",
    cierre: "Captacion exclusiva por 120 dias",
    usuario: "Alejandra Rios",
    observaciones: "Se integra al inventario premium de San Pedro."
  },
  {
    id: "vh-002",
    propiedadClave: "RMX-ACT-201",
    fecha: "2026-03-14",
    valorAnterior: 6980000,
    valorNuevo: 6850000,
    motivo: "Ajuste comercial por comparables",
    cierre: "Continua en promocion activa",
    usuario: "Pedro Leyva",
    observaciones: "Se recalibra ticket para acelerar visitas calificadas."
  },
  {
    id: "vh-003",
    propiedadClave: "RMX-ACT-202",
    fecha: "2025-11-26",
    valorAnterior: null,
    valorNuevo: 5150000,
    motivo: "Alta inicial",
    cierre: "Venta exclusiva",
    usuario: "Daniela Ibarra"
  },
  {
    id: "vh-004",
    propiedadClave: "RMX-ACT-202",
    fecha: "2026-01-18",
    valorAnterior: 5150000,
    valorNuevo: 5050000,
    motivo: "Retroalimentacion de visitas",
    cierre: "Mantener posicion en portal premium",
    usuario: "Daniela Ibarra"
  },
  {
    id: "vh-005",
    propiedadClave: "RMX-ACT-202",
    fecha: "2026-03-09",
    valorAnterior: 5050000,
    valorNuevo: 4920000,
    motivo: "Reposicionamiento de salida",
    cierre: "Apertura a negociacion seria",
    usuario: "Daniela Ibarra"
  },
  {
    id: "vh-006",
    propiedadClave: "RMX-ACT-203",
    fecha: "2026-02-03",
    valorAnterior: null,
    valorNuevo: 98000,
    motivo: "Alta inicial",
    cierre: "Renta mensual + mantenimiento",
    usuario: "Mariana Cisneros"
  },
  {
    id: "vh-007",
    propiedadClave: "RMX-ACT-204",
    fecha: "2025-12-15",
    valorAnterior: null,
    valorNuevo: 75000,
    motivo: "Alta inicial",
    cierre: "Local comercial con exclusividad parcial",
    usuario: "Andres Galvan"
  },
  {
    id: "vh-008",
    propiedadClave: "RMX-ACT-204",
    fecha: "2026-02-28",
    valorAnterior: 75000,
    valorNuevo: 72000,
    motivo: "Ajuste por absorcion de mantenimiento",
    cierre: "Incluye mantenimiento parcial",
    usuario: "Andres Galvan"
  },
  {
    id: "vh-009",
    propiedadClave: "RMX-ACT-205",
    fecha: "2026-01-28",
    valorAnterior: null,
    valorNuevo: 12800000,
    motivo: "Alta inicial",
    cierre: "Venta industrial",
    usuario: "Pedro Leyva"
  },
  {
    id: "vh-010",
    propiedadClave: "RMX-ACT-205",
    fecha: "2026-03-21",
    valorAnterior: 12800000,
    valorNuevo: 12350000,
    motivo: "Ajuste por cierre esperado en Q2",
    cierre: "Operacion en revision avanzada",
    usuario: "Pedro Leyva"
  },
  {
    id: "vh-011",
    propiedadClave: "RMX-ACT-206",
    fecha: "2026-03-04",
    valorAnterior: null,
    valorNuevo: 48000,
    motivo: "Alta inicial",
    cierre: "Renta residencial con poliza",
    usuario: "Karla Soto"
  },
  {
    id: "vh-012",
    propiedadClave: "RMX-ACT-207",
    fecha: "2025-10-18",
    valorAnterior: null,
    valorNuevo: 9500000,
    motivo: "Alta inicial",
    cierre: "Terreno con potencial de desarrollo",
    usuario: "Alejandra Rios"
  },
  {
    id: "vh-013",
    propiedadClave: "RMX-ACT-207",
    fecha: "2026-01-30",
    valorAnterior: 9500000,
    valorNuevo: 9300000,
    motivo: "Salida a mercado revisada",
    cierre: "Se amplian canales de inversionistas",
    usuario: "Alejandra Rios"
  },
  {
    id: "vh-014",
    propiedadClave: "RMX-ACT-207",
    fecha: "2026-03-19",
    valorAnterior: 9300000,
    valorNuevo: 9100000,
    motivo: "Ajuste final para acelerar cierre",
    cierre: "Meta de pipeline de abril",
    usuario: "Valeria Ordonez"
  },
  {
    id: "vh-015",
    propiedadClave: "RMX-ACT-208",
    fecha: "2026-02-18",
    valorAnterior: null,
    valorNuevo: 8500000,
    motivo: "Alta inicial",
    cierre: "Venta residencial exclusiva",
    usuario: "Julieta Mora"
  },
  {
    id: "vh-016",
    propiedadClave: "RMX-ACT-208",
    fecha: "2026-03-07",
    valorAnterior: 8500000,
    valorNuevo: 8350000,
    motivo: "Ajuste comercial despues de open house",
    cierre: "Mejora visibilidad en portal y redes",
    usuario: "Julieta Mora"
  },
  {
    id: "vh-017",
    propiedadClave: "RMX-ACT-209",
    fecha: "2025-09-14",
    valorAnterior: null,
    valorNuevo: 3790000,
    motivo: "Alta inicial",
    cierre: "Exclusividad residencial",
    usuario: "Ricardo Salinas"
  },
  {
    id: "vh-018",
    propiedadClave: "RMX-ACT-209",
    fecha: "2026-02-24",
    valorAnterior: 3790000,
    valorNuevo: 3650000,
    motivo: "Negociacion de cierre",
    cierre: "Oferta aceptada",
    usuario: "Julieta Mora"
  },
  {
    id: "vh-019",
    propiedadClave: "RMX-ACT-210",
    fecha: "2025-12-02",
    valorAnterior: null,
    valorNuevo: 118000,
    motivo: "Alta inicial",
    cierre: "Renta comercial con opcion de expansion",
    usuario: "Mariana Cisneros"
  },
  {
    id: "vh-020",
    propiedadClave: "RMX-ACT-210",
    fecha: "2026-02-14",
    valorAnterior: 118000,
    valorNuevo: 110000,
    motivo: "Paquete de renta anual",
    cierre: "Contrato a 24 meses",
    usuario: "Pedro Leyva"
  },
  {
    id: "vh-021",
    propiedadClave: "RMX-ACT-211",
    fecha: "2025-08-09",
    valorAnterior: null,
    valorNuevo: 5650000,
    motivo: "Alta inicial",
    cierre: "Venta comercial",
    usuario: "Andres Galvan"
  },
  {
    id: "vh-022",
    propiedadClave: "RMX-ACT-211",
    fecha: "2026-01-11",
    valorAnterior: 5650000,
    valorNuevo: 5400000,
    motivo: "Cierre por pago de contado",
    cierre: "Firma notarial programada",
    usuario: "Andres Galvan"
  },
  {
    id: "vh-023",
    propiedadClave: "RMX-ACT-212",
    fecha: "2025-11-05",
    valorAnterior: null,
    valorNuevo: 4100000,
    motivo: "Alta inicial",
    cierre: "Captacion residencial",
    usuario: "Valeria Ordonez"
  },
  {
    id: "vh-024",
    propiedadClave: "RMX-ACT-212",
    fecha: "2026-03-03",
    valorAnterior: 4100000,
    valorNuevo: 3980000,
    motivo: "Ajuste previo a cancelacion",
    cierre: "Cliente retira inventario",
    usuario: "Pedro Leyva"
  },
  {
    id: "vh-025",
    propiedadClave: "RMX-ACT-213",
    fecha: "2026-01-10",
    valorAnterior: null,
    valorNuevo: 135000,
    motivo: "Alta inicial",
    cierre: "Renta mensual",
    usuario: "Tomas Herrera"
  },
  {
    id: "vh-026",
    propiedadClave: "RMX-ACT-214",
    fecha: "2025-12-20",
    valorAnterior: null,
    valorNuevo: 34000,
    motivo: "Alta inicial",
    cierre: "Renta residencial con administracion",
    usuario: "Karla Soto"
  },
  {
    id: "vh-027",
    propiedadClave: "RMX-ACT-214",
    fecha: "2026-03-16",
    valorAnterior: 34000,
    valorNuevo: 32000,
    motivo: "Ultimo ajuste antes de cancelacion",
    cierre: "Sin respuesta del propietario",
    usuario: "Karla Soto"
  }
];

export const remaxDemoCommunications: RemaxCommunication[] = [
  {
    id: "com-001",
    tipo: "ALTA",
    propiedadClave: "RMX-ACT-201",
    fecha: "2026-01-12",
    asunto: "Alta de departamento premium en Valle de San Agustin",
    destinatarios: ["captacion@remaxactiva.mx", "direccion@remaxactiva.mx"],
    estado: "enviado",
    resumen: "Se registra nueva propiedad con Pedro Leyva y Alejandra Rios como responsables de alta."
  },
  {
    id: "com-002",
    tipo: "ALTA",
    propiedadClave: "RMX-ACT-202",
    fecha: "2025-11-26",
    asunto: "Alta de casa residencial en Del Valle",
    destinatarios: ["operaciones@remaxactiva.mx", "direccion@remaxactiva.mx"],
    estado: "enviado",
    resumen: "Expediente inicial aprobado y listo para publicacion con Daniela Ibarra."
  },
  {
    id: "com-003",
    tipo: "ALTA",
    propiedadClave: "RMX-ACT-203",
    fecha: "2026-02-03",
    asunto: "Alta de oficina corporativa en Santa Maria",
    destinatarios: ["rentas@remaxactiva.mx", "recepcion@remaxactiva.mx"],
    estado: "enviado",
    resumen: "Se activa seguimiento comercial para renta de oficinas con apoyo de Mariana Cisneros."
  },
  {
    id: "com-004",
    tipo: "ALTA",
    propiedadClave: "RMX-ACT-204",
    fecha: "2025-12-15",
    asunto: "Alta de local comercial en Cumbres Elite",
    destinatarios: ["captacion@remaxactiva.mx", "marketing@remaxactiva.mx"],
    estado: "enviado",
    resumen: "Local listo para salida en portales con condiciones de renta actualizadas."
  },
  {
    id: "com-005",
    tipo: "ALTA",
    propiedadClave: "RMX-ACT-205",
    fecha: "2026-01-28",
    asunto: "Alta de bodega industrial en Huinala",
    destinatarios: ["industrial@remaxactiva.mx", "direccion@remaxactiva.mx"],
    estado: "enviado",
    resumen: "Pedro Leyva y Tomas Herrera integran propiedad al inventario industrial."
  },
  {
    id: "com-006",
    tipo: "ALTA",
    propiedadClave: "RMX-ACT-206",
    fecha: "2026-03-04",
    asunto: "Alta de casa en renta en Paseo de los Leones",
    destinatarios: ["rentas@remaxactiva.mx", "recepcion@remaxactiva.mx"],
    estado: "pendiente",
    resumen: "Comunicado programado pendiente de adjuntar poliza y fotos finales."
  },
  {
    id: "com-007",
    tipo: "ALTA",
    propiedadClave: "RMX-ACT-207",
    fecha: "2025-10-18",
    asunto: "Alta de terreno para inversion en Carretera Nacional",
    destinatarios: ["inversion@remaxactiva.mx", "direccion@remaxactiva.mx"],
    estado: "enviado",
    resumen: "Se incorpora terreno con estrategia de inversionistas y seguimiento multiasesor."
  },
  {
    id: "com-008",
    tipo: "ALTA",
    propiedadClave: "RMX-ACT-208",
    fecha: "2026-02-18",
    asunto: "Alta de casa residencial en Bosques del Valle",
    destinatarios: ["residencial@remaxactiva.mx", "marketing@remaxactiva.mx"],
    estado: "enviado",
    resumen: "Julieta Mora y Diego Ruiz coordinan salida comercial y open house."
  },
  {
    id: "com-009",
    tipo: "BAJA",
    propiedadClave: "RMX-ACT-209",
    fecha: "2026-03-11",
    asunto: "Cierre de venta de departamento en Contry",
    destinatarios: ["comisiones@remaxactiva.mx", "direccion@remaxactiva.mx"],
    estado: "enviado",
    resumen: "Propiedad marcada como cerrada con cierre apoyado por Julieta Mora y Pedro Leyva."
  },
  {
    id: "com-010",
    tipo: "BAJA",
    propiedadClave: "RMX-ACT-210",
    fecha: "2026-02-27",
    asunto: "Baja por firma de contrato en oficina Fundadores",
    destinatarios: ["operaciones@remaxactiva.mx", "comisiones@remaxactiva.mx"],
    estado: "enviado",
    resumen: "Pedro Leyva participa tanto en alta como en cierre, caso clave para el nuevo modelo de roles."
  },
  {
    id: "com-011",
    tipo: "BAJA",
    propiedadClave: "RMX-ACT-211",
    fecha: "2026-01-22",
    asunto: "Cierre de venta de local en Mitras Norte",
    destinatarios: ["comisiones@remaxactiva.mx", "expedientes@remaxactiva.mx"],
    estado: "borrador",
    resumen: "Comunicado listo para validar anexos notariales antes de enviarse."
  },
  {
    id: "com-012",
    tipo: "CANCELACION",
    propiedadClave: "RMX-ACT-212",
    fecha: "2026-03-08",
    asunto: "Cancelacion de propiedad residencial en Cumbres Madeira",
    destinatarios: ["direccion@remaxactiva.mx", "captacion@remaxactiva.mx"],
    estado: "enviado",
    resumen: "La cancelacion queda trazada con Pedro Leyva y Valeria Ordonez como responsables."
  },
  {
    id: "com-013",
    tipo: "CANCELACION",
    propiedadClave: "RMX-ACT-213",
    fecha: "2026-02-20",
    asunto: "Cancelacion de bodega en renta en La Fe",
    destinatarios: ["industrial@remaxactiva.mx", "recepcion@remaxactiva.mx"],
    estado: "pendiente",
    resumen: "Se detiene publicacion por cambio de decision del propietario y se agenda seguimiento."
  },
  {
    id: "com-014",
    tipo: "CANCELACION",
    propiedadClave: "RMX-ACT-214",
    fecha: "2026-03-17",
    asunto: "Cancelacion de casa en renta en Villas de Anahuac",
    destinatarios: ["rentas@remaxactiva.mx", "operaciones@remaxactiva.mx"],
    estado: "borrador",
    resumen: "Karla Soto aparece tanto en alta como en cancelacion; el nuevo sistema conserva ambos roles."
  }
];

export const remaxDemoProperties: RemaxProperty[] = [
  {
    id: "prop-201",
    clave: "RMX-ACT-201",
    domicilio: "Av. Real San Agustin 245",
    colonia: "Valle de San Agustin",
    ciudad: "San Pedro Garza Garcia",
    municipio: "San Pedro Garza Garcia",
    estado: "Nuevo Leon",
    tipo: "Departamento",
    giro: "Residencial",
    operacion: "Venta",
    estatus: "Activa",
    fechaAlta: "2026-01-12",
    precioActual: 6850000,
    propietario: "Grupo Monteluz",
    asesoresAlta: ["alejandra-rios", "pedro-leyva"],
    asesoresBaja: [],
    asesoresCancelacion: [],
    historialValores: ["vh-001", "vh-002"],
    comunicadoIds: ["com-001"],
    condicionesOperacion: "Venta exclusiva por 120 dias con estrategia premium.",
    fichaResumen: "Departamento de 2 recamaras con amenidades de alto valor para cliente patrimonial."
  },
  {
    id: "prop-202",
    clave: "RMX-ACT-202",
    domicilio: "Calle Acueducto 91",
    colonia: "Del Valle",
    ciudad: "Monterrey",
    municipio: "Monterrey",
    estado: "Nuevo Leon",
    tipo: "Casa",
    giro: "Residencial",
    operacion: "Venta",
    estatus: "Activa",
    fechaAlta: "2025-11-26",
    precioActual: 4920000,
    propietario: "Claudia Benavides",
    asesoresAlta: ["daniela-ibarra"],
    asesoresBaja: [],
    asesoresCancelacion: [],
    historialValores: ["vh-003", "vh-004", "vh-005"],
    comunicadoIds: ["com-002"],
    condicionesOperacion: "Venta con negociacion abierta para pago de contado.",
    fichaResumen: "Casa familiar en zona consolidada con absorcion parcial de gastos notariales."
  },
  {
    id: "prop-203",
    clave: "RMX-ACT-203",
    domicilio: "Blvd. Diaz Ordaz 1880",
    colonia: "Santa Maria",
    ciudad: "Monterrey",
    municipio: "Monterrey",
    estado: "Nuevo Leon",
    tipo: "Oficina",
    giro: "Comercial",
    operacion: "Renta",
    estatus: "Activa",
    fechaAlta: "2026-02-03",
    precioActual: 98000,
    propietario: "Desarrollos Delta Norte",
    asesoresAlta: ["mariana-cisneros", "ricardo-salinas"],
    asesoresBaja: [],
    asesoresCancelacion: [],
    historialValores: ["vh-006"],
    comunicadoIds: ["com-003"],
    condicionesOperacion: "Renta mensual mas mantenimiento y adecuaciones menores.",
    fichaResumen: "Oficina lista para corporativo mediano con acceso directo a vias principales."
  },
  {
    id: "prop-204",
    clave: "RMX-ACT-204",
    domicilio: "Av. Lincoln 4401",
    colonia: "Cumbres Elite",
    ciudad: "Monterrey",
    municipio: "Monterrey",
    estado: "Nuevo Leon",
    tipo: "Local",
    giro: "Comercial",
    operacion: "Renta",
    estatus: "Activa",
    fechaAlta: "2025-12-15",
    precioActual: 72000,
    propietario: "Comercializadora RYH",
    asesoresAlta: ["andres-galvan"],
    asesoresBaja: [],
    asesoresCancelacion: [],
    historialValores: ["vh-007", "vh-008"],
    comunicadoIds: ["com-004"],
    condicionesOperacion: "Renta con absorcion parcial de mantenimiento.",
    fichaResumen: "Local ancla sobre avenida de alto flujo con frente comercial amplio."
  },
  {
    id: "prop-205",
    clave: "RMX-ACT-205",
    domicilio: "Camino a Huinala 870",
    colonia: "Huinala",
    ciudad: "Apodaca",
    municipio: "Apodaca",
    estado: "Nuevo Leon",
    tipo: "Bodega",
    giro: "Industrial",
    operacion: "Venta",
    estatus: "Activa",
    fechaAlta: "2026-01-28",
    precioActual: 12350000,
    propietario: "Logistica Salcedo",
    asesoresAlta: ["pedro-leyva", "tomas-herrera"],
    asesoresBaja: [],
    asesoresCancelacion: [],
    historialValores: ["vh-009", "vh-010"],
    comunicadoIds: ["com-005"],
    condicionesOperacion: "Venta industrial con margen de cierre en segundo trimestre.",
    fichaResumen: "Activo logistico con patio de maniobras y conectividad directa al aeropuerto."
  },
  {
    id: "prop-206",
    clave: "RMX-ACT-206",
    domicilio: "Av. Paseo de los Leones 1187",
    colonia: "Cumbres",
    ciudad: "Monterrey",
    municipio: "Monterrey",
    estado: "Nuevo Leon",
    tipo: "Casa",
    giro: "Residencial",
    operacion: "Renta",
    estatus: "Activa",
    fechaAlta: "2026-03-04",
    precioActual: 48000,
    propietario: "Martha de la Fuente",
    asesoresAlta: ["karla-soto"],
    asesoresBaja: [],
    asesoresCancelacion: [],
    historialValores: ["vh-011"],
    comunicadoIds: ["com-006"],
    condicionesOperacion: "Renta residencial con poliza y deposito en garantia.",
    fichaResumen: "Casa amueblada lista para ejecutivos desplazados por proyectos corporativos."
  },
  {
    id: "prop-207",
    clave: "RMX-ACT-207",
    domicilio: "Carretera Nacional km 261",
    colonia: "La Rioja",
    ciudad: "Monterrey",
    municipio: "Monterrey",
    estado: "Nuevo Leon",
    tipo: "Terreno",
    giro: "Inversion",
    operacion: "Venta",
    estatus: "Activa",
    fechaAlta: "2025-10-18",
    precioActual: 9100000,
    propietario: "Inversiones Lerma",
    asesoresAlta: ["alejandra-rios", "valeria-ordonez"],
    asesoresBaja: [],
    asesoresCancelacion: [],
    historialValores: ["vh-012", "vh-013", "vh-014"],
    comunicadoIds: ["com-007"],
    condicionesOperacion: "Venta para desarrollo mixto con analisis de inversionistas.",
    fichaResumen: "Terreno con frente amplio y narrativa clara para inversionista regional."
  },
  {
    id: "prop-208",
    clave: "RMX-ACT-208",
    domicilio: "Calle Sendero 66",
    colonia: "Bosques del Valle",
    ciudad: "San Pedro Garza Garcia",
    municipio: "San Pedro Garza Garcia",
    estado: "Nuevo Leon",
    tipo: "Casa",
    giro: "Residencial",
    operacion: "Venta",
    estatus: "Activa",
    fechaAlta: "2026-02-18",
    precioActual: 8350000,
    propietario: "Familia Ochoa",
    asesoresAlta: ["julieta-mora", "diego-ruiz"],
    asesoresBaja: [],
    asesoresCancelacion: [],
    historialValores: ["vh-015", "vh-016"],
    comunicadoIds: ["com-008"],
    condicionesOperacion: "Venta con open house y pauta digital.",
    fichaResumen: "Residencia lista para comercializacion premium con narrativa de lifestyle."
  },
  {
    id: "prop-209",
    clave: "RMX-ACT-209",
    domicilio: "Av. Eugenio Garza Sada 5501",
    colonia: "Contry",
    ciudad: "Monterrey",
    municipio: "Monterrey",
    estado: "Nuevo Leon",
    tipo: "Departamento",
    giro: "Residencial",
    operacion: "Venta",
    estatus: "Cerrada",
    fechaAlta: "2025-09-14",
    fechaCierre: "2026-03-11",
    precioActual: 3650000,
    propietario: "Hector Martinez",
    asesoresAlta: ["ricardo-salinas"],
    asesoresBaja: ["julieta-mora", "pedro-leyva"],
    asesoresCancelacion: [],
    historialValores: ["vh-017", "vh-018"],
    comunicadoIds: ["com-009"],
    condicionesOperacion: "Venta cerrada con oferta aceptada y proceso notarial en curso.",
    fichaResumen: "Caso de cierre colaborativo entre asesor junior y liderazgo de direccion."
  },
  {
    id: "prop-210",
    clave: "RMX-ACT-210",
    domicilio: "Av. Fundadores 3010",
    colonia: "Mederos",
    ciudad: "Monterrey",
    municipio: "Monterrey",
    estado: "Nuevo Leon",
    tipo: "Oficina",
    giro: "Comercial",
    operacion: "Renta",
    estatus: "Cerrada",
    fechaAlta: "2025-12-02",
    fechaCierre: "2026-02-27",
    precioActual: 110000,
    propietario: "Operadora Sierra Azul",
    asesoresAlta: ["mariana-cisneros", "pedro-leyva"],
    asesoresBaja: ["pedro-leyva"],
    asesoresCancelacion: [],
    historialValores: ["vh-019", "vh-020"],
    comunicadoIds: ["com-010"],
    condicionesOperacion: "Contrato a 24 meses con opcion de expansion.",
    fichaResumen: "Ejemplo clave de asesor con multiples roles en la misma propiedad."
  },
  {
    id: "prop-211",
    clave: "RMX-ACT-211",
    domicilio: "Av. Ruiz Cortines 1410",
    colonia: "Mitras Norte",
    ciudad: "Monterrey",
    municipio: "Monterrey",
    estado: "Nuevo Leon",
    tipo: "Local",
    giro: "Comercial",
    operacion: "Venta",
    estatus: "Cerrada",
    fechaAlta: "2025-08-09",
    fechaCierre: "2026-01-22",
    precioActual: 5400000,
    propietario: "Inmuebles Vanyor",
    asesoresAlta: ["andres-galvan", "sofia-campos"],
    asesoresBaja: ["andres-galvan"],
    asesoresCancelacion: [],
    historialValores: ["vh-021", "vh-022"],
    comunicadoIds: ["com-011"],
    condicionesOperacion: "Venta de contado con revision legal cerrada.",
    fichaResumen: "Operacion comercial cerrada con continuidad completa del asesor lider."
  },
  {
    id: "prop-212",
    clave: "RMX-ACT-212",
    domicilio: "Calle Nubes 145",
    colonia: "Cumbres Madeira",
    ciudad: "Monterrey",
    municipio: "Monterrey",
    estado: "Nuevo Leon",
    tipo: "Casa",
    giro: "Residencial",
    operacion: "Venta",
    estatus: "Cancelada",
    fechaAlta: "2025-11-05",
    fechaCancelacion: "2026-03-08",
    precioActual: 3980000,
    propietario: "Lorena Fuentes",
    asesoresAlta: ["valeria-ordonez"],
    asesoresBaja: [],
    asesoresCancelacion: ["pedro-leyva", "valeria-ordonez"],
    historialValores: ["vh-023", "vh-024"],
    comunicadoIds: ["com-012"],
    condicionesOperacion: "Expediente cancelado por retiro voluntario del propietario.",
    fichaResumen: "Caso de cancelacion donde el mismo asesor puede quedar trazado desde alta hasta salida."
  },
  {
    id: "prop-213",
    clave: "RMX-ACT-213",
    domicilio: "Av. Miguel Aleman 920",
    colonia: "La Fe",
    ciudad: "San Nicolas de los Garza",
    municipio: "San Nicolas de los Garza",
    estado: "Nuevo Leon",
    tipo: "Bodega",
    giro: "Industrial",
    operacion: "Renta",
    estatus: "Cancelada",
    fechaAlta: "2026-01-10",
    fechaCancelacion: "2026-02-20",
    precioActual: 135000,
    propietario: "Transporte Krest",
    asesoresAlta: ["tomas-herrera"],
    asesoresBaja: [],
    asesoresCancelacion: ["daniela-ibarra"],
    historialValores: ["vh-025"],
    comunicadoIds: ["com-013"],
    condicionesOperacion: "Renta detenida por cambio de decision del propietario.",
    fichaResumen: "Expediente industrial util para mostrar cancelaciones con responsables distintos."
  },
  {
    id: "prop-214",
    clave: "RMX-ACT-214",
    domicilio: "Priv. de las Villas 18",
    colonia: "Villas de Anahuac",
    ciudad: "Escobedo",
    municipio: "Escobedo",
    estado: "Nuevo Leon",
    tipo: "Casa",
    giro: "Residencial",
    operacion: "Renta",
    estatus: "Cancelada",
    fechaAlta: "2025-12-20",
    fechaCancelacion: "2026-03-17",
    precioActual: 32000,
    propietario: "Sandra Morales",
    asesoresAlta: ["karla-soto", "diego-ruiz"],
    asesoresBaja: [],
    asesoresCancelacion: ["karla-soto"],
    historialValores: ["vh-026", "vh-027"],
    comunicadoIds: ["com-014"],
    condicionesOperacion: "Cancelacion por baja respuesta del propietario tras ultimo ajuste.",
    fichaResumen: "Otra muestra donde un asesor conserva su rol de alta y cancelacion en el mismo inmueble."
  }
];
